language: php

php:
  - 5.6

install:
     - composer install --no-interaction --prefer-source

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update




script:
  - vendor/bin/phpunit