language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update

install:
  -composer install --dev


script:
  - vendor/bin/phpunit